// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['app']['App']['DomReady'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function SelectDir() {
  return window['go']['app']['App']['SelectDir']();
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}
