// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {options} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function GetVersion():Promise<string>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenFileExplorer(arg1:string,arg2:string):Promise<void>;

export function SelectDir():Promise<string>;

export function SelectFile():Promise<string>;
