name: Wails Build
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
            {
              name: "Windows-amd64",
              platform: windows/amd64,
              os: windows-latest,
            },
            # { name: "Linux-amd64", platform: linux/amd64, os: ubuntu-latest },
            # {
            #   name: "MacOS-universal",
            #   platform: darwin/universal,
            #   os: macos-latest,
            # },
          ]
    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Wails app
        uses: dAppServer/wails-build-action@main
        with:
          build-name: "DaCapo.exe"
          build-platform: ${{ matrix.build.platform }}
          wails-version: v2.9.2
          go-version: 1.23
          node-version: 22.11
          nsis: true
          package: false

      - name: Debug
        run: |
          dir build/bin

      - name: Get version from tag
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          elif [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "VERSION=dev" >> $GITHUB_ENV
          fi

      - name: Prepare release
        run: |
          mkdir -p DaCapo
          mv build/bin/DaCapo.exe DaCapo/
          powershell Compress-Archive -Path DaCapo -DestinationPath DaCapo-${{ env.VERSION }}-${{ matrix.build.name }}-portable.zip

          mv build/bin/DaCapo-amd64-installer.exe DaCapo-${{ env.VERSION }}-${{ matrix.build.name }}-installer.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event.inputs.tag || github.ref_name }}
          body: |
            仅支持Windows10/11，需自行安装python环境。

            Only supports Windows 10/11. Python environment needs to be installed separately.
          files: |
            DaCapo-${{ env.VERSION }}-${{ matrix.build.name }}-portable.zip
            DaCapo-${{ env.VERSION }}-${{ matrix.build.name }}-installer.exe
